### ISSUE TITLE
マシンスペック確認

### ISSUE THREAD

**Issue by bgpat** [kstm-su/isucon7f#27]
- OS `cat /etc/issue`
- CPU `cat /proc/cpuinfo`
- RAM `cat /proc/meminfo`
- Storage `cat /proc/diskstats`
- Network `iperf`

**Comment by Goryudyuma** [comment]
(Gitで取得できてなかったので、Closeするのは正しいのか？)

**Comment by bgpat** [comment]
結局取れてなかった…
