### ISSUE TITLE
go profile

### ISSUE THREAD

**Issue by Goryudyuma** [kstm-su/isucon7f#43]
(pprof) top -cum
Showing nodes accounting for 1.44s, 5.49% of 26.23s total
Dropped 398 nodes (cum <= 0.13s)
Showing top 10 nodes out of 169
      flat  flat%   sum%        cum   cum%
         0     0%     0%     18.49s 70.49%  main.serveGameConn /home/isucon/webapp/go/src/app/game.go
         0     0%     0%     17.54s 66.87%  main.getStatus /home/isucon/webapp/go/src/app/game.go
     0.14s  0.53%  0.53%     16.11s 61.42%  main.calcStatus /home/isucon/webapp/go/src/app/game.go
     0.33s  1.26%  1.79%     13.85s 52.80%  runtime.systemstack /home/isucon/local/go/src/runtime/asm_amd64.s
     0.66s  2.52%  4.31%      8.09s 30.84%  runtime.mallocgc /home/isucon/local/go/src/runtime/malloc.go
     0.05s  0.19%  4.50%      7.25s 27.64%  math/big.nat.mul /home/isucon/local/go/src/math/big/nat.go
     0.18s  0.69%  5.18%      7.12s 27.14%  math/big.(*Int).Mul /home/isucon/local/go/src/math/big/int.go
     0.05s  0.19%  5.38%      6.78s 25.85%  math/big.nat.mulAddWW /home/isucon/local/go/src/math/big/nat.go
     0.03s  0.11%  5.49%      5.94s 22.65%  runtime.makeslice /home/isucon/local/go/src/runtime/slice.go
         0     0%  5.49%      5.51s 21.01%  runtime.gcBgMarkWorker /home/isucon/local/go/src/runtime/mgc.go
(pprof)

**Comment by bgpat** [comment]
めっちゃ役立った
